using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using WarehouseManagement.BackendServer.Data.Enums;
using WarehouseManagement.BackendServer.Data.Interfaces;

namespace WarehouseManagement.BackendServer.Data.Entities
{
    [Table("Purchases")]
    public class Purchase : IDateTracking, ISoftDelete
    {
        [Key]
        public int Id { get; set; }

        public int? SupplierId { get; set; }

        public string? SupplierName { get; set; }

        public int? CustomerId { get; set; }

        public string? CustomerName { get; set; }

        public bool IsExport { get; set; }

        public int Type { get; set; } // 1: Nhập, 2: Xuất

        public DateTime? PurchaseDate { get; set; }

        public PurchaseStatus Status { get; set; }

        [Precision(18, 2)]
        public decimal TotalCost { get; set; }

        // Human readable receipt code generated by server, e.g. PO-202605-001
        [MaxLength(50)]
        public string? ReceiptCode { get; set; }

        // Optional reference code provided by user
        [MaxLength(100)]
        public string? ReferenceCode { get; set; }

        public string? Note { get; set; }

        public bool IsCanceled { get; set; }

        public string? CancelReason { get; set; }

        public DateTime? CanceledDate { get; set; }

        public string? CanceledBy { get; set; }

        public string? ApprovedBy { get; set; }

        public DateTime? ApprovedDate { get; set; }

        public DateTime CreateDate { get; set; }

        // Identity user id who created the purchase
        [MaxLength(450)]
        public string? CreatedBy { get; set; }

        public DateTime? LastModifiedDate { get; set; }

        public bool IsDeleted { get; set; } = false;

        public ICollection<PurchaseItem> PurchaseItems { get; set; } = new List<PurchaseItem>();
    }
}
